devtools::load_all()

# Test sparkline() function
test1 <- c(1, 2, 3, 4, 5, 6, 7, 8, 7, 6, 5, 4, 3, 2, 1)
sparkline(test1)
sparkline_bar(test1)
sparkline(test1, chart = "tally")
sparkline_line(test1)
sparkline_shade(test1)
sparkline_area(test1)

test2 <- c(1.5, 0.5, 3.5, 2.5, 5.5, 4.5, 7.5, 6.5)
sparkline(test2)
sparkline_bar(test2)
sparkline(test2, chart = "tally")
sparkline_line(test2)
sparkline_shade(test2)
sparkline_area(test2)

test3 <- c(0, 0, 1, 1)
sparkline(test3)
sparkline_bar(test3)
sparkline(test3, chart = "tally")
sparkline_line(test3)
sparkline_shade(test3)
sparkline_area(test3)

test4 <- c(0, 1, 19, 20)
sparkline(test4)
sparkline_bar(test4)
sparkline(test4, chart = "tally")
sparkline_line(test4)
sparkline_shade(test4)
sparkline_area(test4)

test5 <- rev(test2)
sparkline(test5)
sparkline_bar(test5)
sparkline(test5, chart = "tally")
sparkline_line(test5)
sparkline_shade(test5)
sparkline_area(test5)
