devtools::load_all()

# Test sparkline() function
test1 <- c(1, 2, 3, 4, 5, 6, 7, 8, 7, 6, 5, 4, 3, 2, 1)
sparkline(test1)
sparkline_bars(test1)
sparkline(test1, chars = "lines")
sparkline_lines(test1)
sparkline_area(test1)

test2 <- c(1.5, 0.5, 3.5, 2.5, 5.5, 4.5, 7.5, 6.5)
sparkline(test2)
sparkline_bars(test2)
sparkline(test2, chars = "lines")
sparkline_lines(test2)
sparkline_area(test2)

test3 <- c(0, 0, 1, 1)
sparkline(test3)
sparkline_bars(test3)
sparkline(test3, chars = "lines")
sparkline_lines(test3)
sparkline_area(test3)

test4 <- c(0, 1, 19, 20)
sparkline(test4)
sparkline_bars(test4)
sparkline(test4, chars = "lines")
sparkline_area(test4)
sparkline_lines(test4)
